export const CATEGORY_LOADING = "CATEGORY_LOADING"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_ERROR = "CATEGORY_ERROR"
export const CATEGORY_LIST = "CATEGORY_LIST"
export const CATEGORY_DELETE = "CATEGORY_DELETE"
export const CATEGORY_UPDATE = "CATEGORY_UPDATE"
export const CATEGORY_INSERT = "CATEGORY_INSERT"



export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_DELETE = "PRODUCT_DELETE"
export const PRODUCT_INSERT = 'PRODUCT_INSERT'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'


export const GALLARY_LOADING = 'GALLARY_LOADING'
export const GALLARY_SUCCESS = 'GALLARY_SUCCESS'
export const GALLARY_ERROR = 'GALLARY_ERROR'
export const GALLARY_LIST = "GALLARY_LIST"
export const GALLARY_DELETE = "GALLARY_DELETE"
export const GALLARY_INSERT = 'GALLARY_INSERT'
export const GALLARY_UPDATE = 'GALLARY_UPDATE'



